## 241227 수업시작!

In [1]:
score = int(input())

message = "success" if score >= 60 else "failure"
print(message)

success


In [3]:
numbers = [50, 8, 7, 66, 15]
squares = []
for x in numbers:
    squares.append(x**2)

squares = [x**2 for x in numbers]
print(squares)

[2500, 64, 49, 4356, 225]


In [6]:
numbers = [1, 2, 3, 4, 5, 6, 7]

even_numbers = [i for i in numbers if i%2 ==0]
print(even_numbers)

[2, 4, 6]


In [7]:
numbers = [1, 2, 3, 4, 5, 6, 7]

even_numbers = [i**2 for i in numbers if i%2 ==0]
print(even_numbers)

[4, 16, 36]


## Numpy

In [10]:
pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----------------------- ---------------- 7.3/12.6 MB 37.1 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 34.4 MB/s eta 0:00:00


In [11]:
import numpy as np

In [12]:
np.__version__

'2.2.1'

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
arr1 = np.arange(1, 10, 2)
arr1

array([1, 3, 5, 7, 9])

In [16]:
arr = np.zeros(10, dtype= int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [18]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],
               [[9,10,11,12],[13,14,15,16]],
               [[9,10,11,12],[13,14,15,16]]])

print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
(3, 2, 4)


In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [24]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

x = np.array(data)
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
a = np.array([[0,1,2],[3,4,5]])

print(a[0][0], a[0][1], a[1,2])

0 1 5


In [39]:
a= np.array([[0, 1, 2, 3],[4, 5, 6, 7]])

print(a[0])

[0 1 2 3]


In [30]:
print(a[0][1], a[1][1])

1 5


In [31]:
print(a[:, 1])

[1 5]


In [34]:
print(a[1, 1:])

[5 6 7]


In [41]:
print(a[:2, :2])

[[0 1]
 [4 5]]


In [43]:
a=np.array([1, 2, 3])
b=np.array([10, 20, 30])

print(2*a+b)
print(a == 2)
print(b >10)
print((a==2)&(b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [49]:
a= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,False, True, False, True, False])

print(a[idx])
print(a.size)

[0 2 4 6 8]
10


In [54]:
a= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[a%2 == 0]
# array([ True, False,  True, False,  True, False,  True, False,  True, False])

array([0, 2, 4, 6, 8])

In [73]:
a= np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [74]:
a[:, 0]

array([1, 5, 9])

In [75]:
a[[0, 1, 2], [0, 0, 0]]

array([1, 5, 9])

## Pandas

In [76]:
pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------- ----------------------- 4.7/11.5 MB 24.2 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 28.6 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 26.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [77]:
import pandas as pd

In [78]:
pd.__version__

'2.2.3'

In [82]:
s= pd.Series([3, -5, 7, 4], index =['a', 'b', 'c', 'd'])
print(s)
print(type(s)) 

a    3
b   -5
c    7
d    4
dtype: int64
<class 'pandas.core.series.Series'>


In [84]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [85]:
s.values

array([ 3, -5,  7,  4])

In [90]:
print(s[0])

3


C:\Users\wlsth\AppData\Local\Temp\ipykernel_21208\287792665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [89]:
s['c']

np.int64(7)

In [91]:
s

a    3
b   -5
c    7
d    4
dtype: int64

In [92]:
s*3

a     9
b   -15
c    21
d    12
dtype: int64

In [97]:
df = pd.DataFrame({'Division':['부산광역시', '전라남도', '강원도'],  'Code':['051', '061', '033'], 'Population' : [3364358, 1840921, 1535530]})


print(type(df))
display(df)

<class 'pandas.core.frame.DataFrame'>


Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530

In [102]:
df.index = df['Division']
df

Division Code  Population
Division                          
부산광역시       부산광역시  051     3364358
전라남도         전라남도  061     1840921
강원도           강원도  033     1535530

# 데이터 가져오기

In [110]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+10
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [112]:
pd.options.display.float_format = '{:.0f}'.format
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [117]:
df.head(5)

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [118]:
df.tail()

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [119]:
df.describe()

나이   키          재산
count   7   7           5
mean   34 190  2578000120
std    13  36  5003440739
min    18 170         600
25%    26 172    50000000
50%    32 177   340000000
75%    39 184  1000000000
max    58 270 11500000000

In [121]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [122]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [125]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [129]:
df.nlargest(5, '나이')

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
6  블랙위도우  32    스파이    러시아  170    50000000
3   원더우먼  27     공주  데미스키라  178         NaN

In [133]:
df.nlargest(7, '키')

이름  나이     직업     국적    키          재산
4     헐크  33  핵물리학자     미국  270  1000000000
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN
2  스파이더맨  18   고등학생     미국  177         600
0   아이언맨  58    CEO     미국  174 11500000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [146]:
df[['이름', '직업', '키']].nlargest(6, '키')

이름     직업    키
4     헐크  핵물리학자  270
1     토르      신  190
3   원더우먼     공주  178
2  스파이더맨   고등학생  177
0   아이언맨    CEO  174
5   캡틴마블    파일럿  170

In [147]:
df['이름']

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
5     캡틴마블
6    블랙위도우
Name: 이름, dtype: object

In [148]:
df[0:2]

이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

## 특정 데이터 조회해서 가져오기

In [152]:
df.iloc[2, 2] #데이터프레임명.iloc[행번호, 열번호호]

'고등학생'

In [153]:
df.iloc[0]

이름          아이언맨
나이            58
직업           CEO
국적            미국
키            174
재산   11500000000
Name: 0, dtype: object

In [151]:
df.loc[0, '이름'] #데이터프레임명.loc[인덱스명, 칼럼명]

'아이언맨'

In [154]:
df.iloc[[1,2,3]]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [158]:
df[(df['나이']>30) & (df['나이']<50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [156]:
df['나이']>30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [162]:
df.loc[(df['나이']>30) &(df['나이']<50), '이름':'직업']

#loc를 사용해서 정렬하는 법

이름  나이     직업
1     토르  45      신
4     헐크  33  핵물리학자
6  블랙위도우  32    스파이

In [165]:
df.sort_values('키')

이름  나이     직업     국적    키          재산
6  블랙위도우  32    스파이    러시아  170    50000000
5   캡틴마블  25    파일럿     미국  170   340000000
0   아이언맨  58    CEO     미국  174 11500000000
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
1     토르  45      신  아스가르드  190         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [166]:
df.sort_values('재산', ascending=False) #내림차순

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000
2  스파이더맨  18   고등학생     미국  177         600
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN

In [170]:
df2 = df
df2['국적'] = '대한민국'
df2

이름  나이     직업    국적    키          재산
0   아이언맨  58    CEO  대한민국  174 11500000000
1     토르  45      신  대한민국  190         NaN
2  스파이더맨  18   고등학생  대한민국  177         600
3   원더우먼  27     공주  대한민국  178         NaN
4     헐크  33  핵물리학자  대한민국  270  1000000000
5   캡틴마블  25    파일럿  대한민국  170   340000000
6  블랙위도우  32    스파이  대한민국  170    50000000

In [178]:
df2.columns = ['성명', '연령', '하는일', '출신국가', '신장', '재산현황', '파워']
df2

#컬럼명 전체 변경

성명  연령    하는일  출신국가   신장        재산현황  파워
0   아이언맨  48    CEO  대한민국  174 11500000000  53
1     토르  35      신  대한민국  190         NaN  40
2  스파이더맨   8   고등학생  대한민국  177         600  13
3   원더우먼  17     공주  대한민국  178         NaN  22
4     헐크  23  핵물리학자  대한민국  270  1000000000  28
5   캡틴마블  15    파일럿  대한민국  170   340000000  20
6  블랙위도우  22    스파이  대한민국  170    50000000  27

In [184]:
df2.drop(index=[1], inplace=True)
df2

성명  연령    하는일  출신국가   신장       재산현황  파워
2  스파이더맨   8   고등학생  대한민국  177        600  13
3   원더우먼  17     공주  대한민국  178        NaN  22
4     헐크  23  핵물리학자  대한민국  270 1000000000  28
5   캡틴마블  15    파일럿  대한민국  170  340000000  20
6  블랙위도우  22    스파이  대한민국  170   50000000  27

In [186]:
df2.drop(columns=['신장'], inplace=True)
df2

성명  연령    하는일  출신국가       재산현황  파워
2  스파이더맨   8   고등학생  대한민국        600  13
3   원더우먼  17     공주  대한민국        NaN  22
4     헐크  23  핵물리학자  대한민국 1000000000  28
5   캡틴마블  15    파일럿  대한민국  340000000  20
6  블랙위도우  22    스파이  대한민국   50000000  27

In [189]:
df2.dropna(axis=1) 

#결측치가 들어있는 행을 모두 지울 수 있음 
#axis는 축

성명  연령    하는일  출신국가  파워
2  스파이더맨   8   고등학생  대한민국  13
3   원더우먼  17     공주  대한민국  22
4     헐크  23  핵물리학자  대한민국  28
5   캡틴마블  15    파일럿  대한민국  20
6  블랙위도우  22    스파이  대한민국  27

#### 데이터 정렬: df.sort_values()
#### 중복 제거: df.drop_duplicates()
#### 결측치 처리: df.fillna(), df.dropna()
#### 열/행 삭제: df.drop()

In [191]:
df2.fillna(0) #결측치를 0으로 채움

성명  연령    하는일  출신국가       재산현황  파워
2  스파이더맨   8   고등학생  대한민국        600  13
3   원더우먼  17     공주  대한민국          0  22
4     헐크  23  핵물리학자  대한민국 1000000000  28
5   캡틴마블  15    파일럿  대한민국  340000000  20
6  블랙위도우  22    스파이  대한민국   50000000  27

In [195]:
df2.fillna(method='ffill') #결측치 처리 이전의 값으로 

C:\Users\wlsth\AppData\Local\Temp\ipykernel_21208\2637571705.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='ffill') #결측치 처리 이전의 값으로


성명  연령    하는일  출신국가       재산현황  파워
2  스파이더맨   8   고등학생  대한민국        600  13
3   원더우먼  17     공주  대한민국        600  22
4     헐크  23  핵물리학자  대한민국 1000000000  28
5   캡틴마블  15    파일럿  대한민국  340000000  20
6  블랙위도우  22    스파이  대한민국   50000000  27

In [196]:
df2['재산현황'].mean()

np.float64(347500150.0)

In [199]:
df2['재산현황'].fillna(df2['재산현황'].mean())
df2

성명  연령    하는일  출신국가       재산현황  파워
2  스파이더맨   8   고등학생  대한민국        600  13
3   원더우먼  17     공주  대한민국        NaN  22
4     헐크  23  핵물리학자  대한민국 1000000000  28
5   캡틴마블  15    파일럿  대한민국  340000000  20
6  블랙위도우  22    스파이  대한민국   50000000  27